# git abbrevations

abbr -a g "git"
abbr -a ga "git add"
abbr -a gaa "git add --all"
abbr -a gb "git branch -v"
abbr -a gc "git commit -s"
abbr -a gca "git commit -sa"
abbr -a gcm "git commit -sm"
abbr -a gcam "git commit -sam"
abbr -a gco "git checkout"
abbr -a gcob "git checkout -b"
abbr -a gcp "git cherry-pick"
abbr -a gd "git diff"
abbr -a gm "git merge --no-ff"
abbr -a gl "git pull --prune"
abbr -a gp "git push origin HEAD"
abbr -a gpa "git push origin --all"
abbr -a gpt "git push --tags"
abbr -a grh "git reset --hard"
abbr -a gs "git status -sb"
abbr -a gsu "git status -uno"
abbr -a gw "git switch"
abbr -a gwc "git switch -c"
