add_newline = true

format = """\
  $time\
  $username\
  $hostname\
  $directory\
  $nix_shell\
  $memory_usage\
  $env_var\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $cmd_duration\
  $custom\
  $line_break\
  $jobs\
  $character\
  """

[character]
format="$symbol "
error_symbol="[»](bold #ff5555)"
success_symbol="[»](bold  #50fa7b)"

[cmd_duration]
style = "bold #f1fa8c"
min_time=6_000

[directory]
format = "in [$path]($style)[$read_only]($read_only_style) "
style = "bold #50fa7b"

[git_branch]
style = "bold #ff79c6"

[git_status]
style = "bold #ff5555"

[time]
disabled = false
format="at [$time]($style) "
style = "bold blue"
time_format = "%T"

[username]
format = "[$user]($style) on "
style_user = "bold #8be9fd"