on:
  push:
    paths:
      - "**.nix"
      - "**.lock"
  workflow_dispatch:
  
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check --show-trace --accept-flake-config
