name: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository    
        uses: actions/checkout@v4
      
      - name: Install Nix      
        uses: DeterminateSystems/nix-installer-action@main
      
      - uses: DeterminateSystems/magic-nix-cache-action@main
      
      - name: Check flake
        run: nix flake check --show-trace --accept-flake-config
