name: ci
on:
  pull_request:
  push:
    paths:
      - "**.lock"
      - "**.nix"
  workflow_dispatch:
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix flake check --show-trace --accept-flake-config
